### ISSUE TITLE
Provide more info about the different monsters

### ISSUE THREAD

**Issue by krnekhelesh** [t-mon/monsterwars#1]
There are strength, reproduction, speed and defense monsters. How do they affect each other? What does having more strength do? Reduce the impact of pillows on them? This is a bit unclear.

**Comment by t-mon** [comment]
There is a in app tutorial planed. The property points of each monster can be interpreted as following:
- If you trough a pillow with a strength monster (i.e. pillow count 20) it will hurt the target monster (normal monster) with 25 points. If the target monster would be a defense monster -> 20.
- If you throw a pollow from a normal monster to a defense target monster  with a 20 pillow, it will only hurt 15 points.
- If you throw a pollow with a speed monster, it's flying much faster (important for strategy)
- if you have a reproduction monster, it will count up much faster the points than the other monsters. 

....

your monster properties (from the settings) will be added to each monster. Thats it :)

**Comment by nikwen** [comment]
Do monsters have a maximum number of points? At some point it looked like that to me.

**Comment by t-mon** [comment]
Yes, depending on the size of the monster! a big monster can hold more pillows than a small one. 

`maxPoints = 40 + monstersize * 10  | [ 3 < monstersize < 8]`

However, there appears sometimes a bug and some monster stop randomly counting...this bug is hidden very good...still not found the problem.

**Comment by nikwen** [comment]
Cool, thank you for the info. :)

(What might be of interest for the bug is that when this happens once, it seems to happen again all the time when restarting or selecting a new level until the app is restarted.)

**Comment by t-mon** [comment]
finally found and fixed the "randomly stop counting" bug...it was very well hidden :)

**Comment by nikwen** [comment]
Nice! That's great to hear. :)
