### ISSUE TITLE
Please publish app for arm64 and amd64, too

### ISSUE THREAD

**Issue by jonnius** [t-mon/monsterwars#18]
Doing so is easy:

- [ ] Make sure you Clickable is up-to-date (should be >= 6.6)
- [ ] Make sure your Clickable images are up-to-date with `clickable update`
- [ ] Build for all architectures
```
clickable build --arch armhf
clickable build --arch arm64
clickable build --arch amd64
```
- [ ] Publish for all architectures
```
clickable publish --arch armhf --apikey <OPENSTORE_KEY>
clickable publish --arch arm64 --apikey <OPENSTORE_KEY>
clickable publish --arch amd64 --apikey <OPENSTORE_KEY>
```

**Comment by MenmuirMark** [comment]
I built it locally for arm64 on Ubuntu Touch on the Raspberry Pi and it seems to work fine. It should also work on the Pinephone and other arm64 devices.

**Comment by t-mon** [comment]
worked now and is published. Thanks for the hint

**Comment by jonnius** [comment]
The app is no longer available for either architecture. Did you unpublish it accidentially?

**Comment by t-mon** [comment]
hmm, should be available now? at least I can find it in the store and all apps are on "published".

**Comment by jonnius** [comment]
I can find it, too. But it shows _"No longer available"_ and offers no downloads, not even the `armhf` one. Do you see revisions in the stats tab? If you think this is an issue with the OpenStore you could open an issue on the [Bug Tracker](https://gitlab.com/theopenstore/openstore-meta/issues).

**Comment by MenmuirMark** [comment]
![screenshot20200420_152720060](https://user-images.githubusercontent.com/35196780/79763199-aa230980-831b-11ea-90bb-d9ff98b379df.png)

**Comment by MenmuirMark** [comment]
On my OPO it won't install giving the error above. On the Pi it can't find it in the Open Store. On Openstore on the browser is says no longer available. Something funny somewhere.

**Comment by jonnius** [comment]
@t-mon are you trying to upload a multi-arch click package?

**Comment by t-mon** [comment]
hmm, actually, the monsterwars click still the old one for xenial (multiarch, yes), and a vivid version does not seem to have any architecture...something went wrong here. I probably need to rebuild all of them and replace the packages...

**Comment by t-mon** [comment]
I updated all packages in the open-store. Please let me know if they work for you.
