### ISSUE TITLE
Be able to change the allocation of available points

### ISSUE THREAD

**Issue by krnekhelesh** [t-mon/monsterwars#2]
As you begin to understand the game more, you realize may be you allocated points corrects. Perhaps a minus (-) button to remove the allocation from a specific category and use them in other category would be nice to have.

**Comment by t-mon** [comment]
The levels are designed to get more difficult in different properties (i.e. one level is speed very important, in an other defence). A (-) button would destroy that concept. It would be to easy if you can balance your point for each level :)

**Comment by krnekhelesh** [comment]
Ah okay that makes sense. In that case, could you atleast allow to correct our point allocation. sometimes I mistakingly allocate incorrectly. So I need to adjust it at the moment. After I leave that page, you can lock it and ensure no further changes can be made.

**Comment by t-mon** [comment]
you mean an "undo" button until you leaf the settings page? that would help, yes :) thank you

**Comment by krnekhelesh** [comment]
Yup an "undo" button should do the trick until I leave the settings page.
