### ISSUE TITLE
Level 10 stays locked although I completed level 9

### ISSUE THREAD

**Issue by nikwen** [t-mon/monsterwars#3]
First of all, thank you for this awesome game!

Sadly, I cannot unlock level 9. I played that one before the last update (looked like a dummy level to me) and now after completing the "real" level 9, level 10 does not get unlocked. You might run into the same issue with level 11/12 in the future.

**Comment by t-mon** [comment]
Thank you for the bug report! This issue is already fixed and will be disappear in v 0.3!
In the meantime you can "cheat" if you want by adding following lines in the the config file of Monster Wars on the phone:

`nano ~/.config/monsterwars.t-mon/monsterwars.t-mon.conf`

```
[Level%2010]
unlocked=true
```

**Comment by nikwen** [comment]
I just deleted the level 9 entry from the file to do this. :D
Thanks for fixing this anyway. :)

**Comment by nikwen** [comment]
(Oh,  I need to readd it with only the unlocked line …)

**Comment by t-mon** [comment]
:) that should do the trick too! but you have to replay level 9

**Comment by nikwen** [comment]
True. Afterwards, I'll have a valid highscore though instead of the 4 seconds record that I had for the dummy level. ;)

**Comment by t-mon** [comment]
oh, have you compiled the src or used the app store version? have I forgotten a testing level in the release?

**Comment by nikwen** [comment]
It was version 0.1 from the store. Level 9 were two monsters in the upper left corner starting at around 60 points.

**Comment by t-mon** [comment]
sorry for that...I had upload the game for the UbuContest and forgot to remove that level. :) 
more levels coming soon!

**Comment by nikwen** [comment]
Don't worry. It's a great game and thanks for publishing its source code online!
