### ISSUE TITLE
Undo button does not give point back

### ISSUE THREAD

**Issue by nikwen** [t-mon/monsterwars#5]
How to reproduce:

1) Complete a level for the first time
2) Get one new point to spend on skills
3) Add it to one category
4) Use the undo button

What happens:

The value of the category is decreased by one. However, I didn't get the point back.

**Comment by t-mon** [comment]
Fixed with version V 0.4! Please make an update! :)

**Comment by nikwen** [comment]
Ok, thanks. Just finished editing this when you replied. (Initially tried to write this on my phone.) :D

**Comment by t-mon** [comment]
hehe :D

**Comment by t-mon** [comment]
I totally panicked when I discovered this bug...it was 12h in the store, and 72 people got this bug.

**Comment by nikwen** [comment]
I would probably also have done that. :D
I manually readded the point to the config file. ;)
