### ISSUE TITLE
[bitesize] Padding of "x" icon in the main page is inconsistent

### ISSUE THREAD

**Issue by krnekhelesh** [t-mon/monsterwars#8]
I noticed that the padding of icons is a bit inconsistent in several places. For instance, in the main page, the icons "info", "settings" and "sound" have uniform vertical padding from the bottom edge. However the "close" icon on the top does not have the same left and top padding making it look inconsistent. A tiny bitesize issue ;)

**Comment by t-mon** [comment]
The settings button is a little bit bigger by design, fixed the _close_ icon.
