### ISSUE TITLE
Monster can reach points count of 0 by throwing pillows

### ISSUE THREAD

**Issue by nikwen** [t-mon/monsterwars#9]
How to reproduce:

1) Launch level 26.
2) Rapidly throw as many pillows as possible from one monster to another.
3) Eventually, the monster will reach 0 points if you are fast enough.

In my opinion (3) should never happen.

(Additionally, the monster does not generate any new points for you but it still stays blue.)

![screenshot20151017_165840702](https://cloud.githubusercontent.com/assets/3309657/10559410/b1084672-74f0-11e5-8780-d12ffab94219.png)

**Comment by nikwen** [comment]
Thanks for fixing! :smiley:

**Comment by nikwen** [comment]
Would you mind explaining how exactly you solved it in the commit? Is player number 0 the player or the AI?

```
if (m_value == 0 && player()->id() == 0)
```

I.e. does it still count upwards now, will it be impossible to throw the last pillow or will the monster simply turn colorless now?

**Comment by t-mon** [comment]
:) player 0 is the white dummy player, which has no points and no player. He exists only for the sleeping (sleeping animation in progress) monsters which can be conquered by everyone.

This line makes shore, that the counting will only stop if the value is 0 and the monster is white. A monster can "now" only turn white if an attack destroys all points from the enemy. 

The "story" behind this behaviour: once a monster has no more pillows, it doesn't know any more in which team it should play, and goes to sleep (animation in progress), until some other monster gives him some pillows to return back to the game -> for the team which "gave" the pillows. :D

**Comment by nikwen** [comment]
Cool, thank you very much for the explanation. :)

And for the great game again, of course. :D
